steps:
- name: "gcr.io/cloud-builders/gsutil"
  args: ['cp', 'gs://${_ML_MODELS_BUCKET}/iris/*latest', '${_MODEL_ARCHIVE}']
  dir: /workspace

- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     ML_MODELS_BUCKET="${PROJECT_ID}-models"
     sed -e "s/\$$PROJECT_ID/$PROJECT_ID/g" \
         -e "s/\$$ML_MODELS_BUCKET/$$ML_MODELS_BUCKET/g" app.yaml.tmpl > app.yaml
     cat app.yaml
     gcloud app deploy --project ${_ANALYTICS_PROJECT}
  dir: /workspace

substitutions:
    _MODEL_ARCHIVE: iris.joblib

timeout: "1600s"
