steps:
- name: "gcr.io/cloud-builders/gsutil"
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     gsutil cp gs://$$ML_MODELS_BUCKET/iris/*latest $$MODEL_ARCHIVE
  dir: /workspace

- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed -e "s/\$$PROJECT_ID/$PROJECT_ID/g" \
         -e "s/\$$ML_MODELS_BUCKET/$$ML_MODELS_BUCKET/g" app.yaml.tmpl > app.yaml
     cat app.yaml
     gcloud app deploy --project ${_ANALYTICS_PROJECT}
  dir: /workspace

options:
    env:
    - ML_MODELS_BUCKET=${_ANALYTICS_PROJECT}-models
    - MODEL_ARCHIVE=iris.joblib

timeout: "1600s"
